//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbControlDinero
    {
        public string Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Monto { get; set; }
        public int Tipo { get; set; }
        public string Factura { get; set; }
    
        public virtual tbFactura tbFactura { get; set; }
    }
}
