//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleFactura
    {
        public int Id { get; set; }
        public string IdProductos { get; set; }
        public string IdFactura { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int Cantiadad { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual tbFactura tbFactura { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
