//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFactura()
        {
            this.tbControlDinero = new HashSet<tbControlDinero>();
        }
    
        public string IdFactura { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int Tipo { get; set; }
        public string Productos { get; set; }
        public Nullable<int> TipoAsocie { get; set; }
        public string IdCliente { get; set; }
        public string IdProveedor { get; set; }
        public string NombreAsocie { get; set; }
        public decimal Total { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbControlDinero> tbControlDinero { get; set; }
        public virtual tbProveedor tbProveedor { get; set; }
    }
}
