//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersona
    {
        public string Id { get; set; }
        public int TipoId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefeno { get; set; }
        public string Correo { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbProveedor tbProveedor { get; set; }
    }
}
