//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProveedorFactura
    {
        public int id { get; set; }
        public string IdProveedor { get; set; }
        public string IdFactura { get; set; }
    
        public virtual tbFactura tbFactura { get; set; }
        public virtual tbProveedor tbProveedor { get; set; }
    }
}
